[book]
authors = ["Hieu Nguyen"]
language = "en"
multilingual = false
src = "src"
title = "A Localized Method for the Multi-commodity Flow Problem"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/nthieu173/localized-multicommodity-flow/tree/main"
edit-url-template = "https://github.com/nthieu173/localized-multicommodity-flow/edit/main/{path}"
mathjax-support = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
